/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedModelEntityModelPostEmbedded } from './pagedModelEntityModelPostEmbedded';
import { Link } from './link';


export interface CollectionModelEntityModelPost { 
    _embedded?: PagedModelEntityModelPostEmbedded;
    _links?: { [key: string]: Link; };
}

