/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';
import { CollectionModelObjectEmbedded } from './collectionModelObjectEmbedded';


export interface CollectionModelObject { 
    _embedded?: CollectionModelObjectEmbedded;
    _links?: { [key: string]: Link; };
}

