/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


export interface EntityModelPost { 
    title?: string;
    content?: string;
    createdAt?: string;
    _links?: { [key: string]: Link; };
}

