/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityModelPost } from './entityModelPost';


export interface PagedModelEntityModelPostEmbedded { 
    posts?: Array<EntityModelPost>;
}

