/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { PagedModelEntityModelUserEmbedded } from './pagedModelEntityModelUserEmbedded';
import { Link } from './link';


export interface PagedModelEntityModelUser { 
    _embedded?: PagedModelEntityModelUserEmbedded;
    _links?: { [key: string]: Link; };
    page?: PageMetadata;
}

