/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Aktualisierte Details des Posts
 */
export interface PostUpdateDto { 
    title: string;
    content: string;
}

