/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO zur Anzeige einer Übersicht eines Post\'s
 */
export interface PostShowDto { 
    id: number;
    title: string;
    content: string;
    userId: number;
    createdAt: string;
}

