/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details des zu erstellenden Benutzers.
 */
export interface UserCreateDto { 
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    /**
     * Automatisch auf \'USER\' gesetzt
     */
    readonly role?: string;
}

